asyncio - ERROR - SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x7ff8aa7ad7f0>
transport: <_SelectorSocketTransport fd=111 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 632, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 677, in _process_write_backlog
    ssldata = self._sslpipe.do_handshake(
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 117, in do_handshake
    self._sslobj = self._context.wrap_bio(
  File "/usr/lib/python3.8/ssl.py", line 516, in wrap_bio
    server_hostname=self._encode_hostname(server_hostname),
  File "/usr/lib/python3.8/ssl.py", line 490, in _encode_hostname
    return hostname.encode('idna').decode('ascii')
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
asyncio - ERROR - SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x7ff8aa79c5b0>
transport: <_SelectorSocketTransport fd=112 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 632, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 677, in _process_write_backlog
    ssldata = self._sslpipe.do_handshake(
  File "/usr/lib/python3.8/asyncio/sslproto.py", line 117, in do_handshake
    self._sslobj = self._context.wrap_bio(
  File "/usr/lib/python3.8/ssl.py", line 516, in wrap_bio
    server_hostname=self._encode_hostname(server_hostname),
  File "/usr/lib/python3.8/ssl.py", line 490, in _encode_hostname
    return hostname.encode('idna').decode('ascii')
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
